name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    workflow_dispatch:
    
env:
  TELEGRAM_API_KEY: "${{ secrets.TELEGRAM_API_KEY }}"
  ALLOWED_USERS: "${{ secrets.ALLOWED_USERS }}"
  TELEGRAM_USER_ID: "${{ secrets.TELEGRAM_USER_ID }}"
  SERP_API_KEY: "${{ secrets.SERP_API_KEY }}"
  OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
            ref: main
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true

         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends ffmpeg neofetch
           pip3 install -r requirements.txt
          #  echo "TELEGRAM_API_KEY=${{ secrets.TELEGRAM_API_KEY }} | tee .env
          #  echo "ALLOWED_USERS=${{ secrets.ALLOWED_USERS }} | tee -a .env
          #  echo "TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }} | tee -a .env 
          #  echo "SERP_API_KEY=${{ secrets.SERP_API_KEY }} | tee -a .env 
          #  echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} | tee -a .env || echo "Proceeding with no bot"
          #  cat .env
       - name: Running
         timeout-minutes: 360
         continue-on-error: true
         run: |
           python main.py
           echo "Bot Died"
